services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: acoustic_rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rmq_data:/var/lib/rabbitmq
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 5s
      timeout: 5s
      retries: 5

  edge-agent:
    build:
      context: ../edge-agent
      dockerfile: Dockerfile
    container_name: acoustic_edge_agent
    restart: unless-stopped
    environment:
      - AMQP_URI=amqp://guest:guest@rabbitmq:5672/%2f
      - HUB_URL=http://java-hub:8080/api/v1 # Artem, vstav siudy svoiu urlu
      - DEVICE_ID=node-001
      - LOOP_INTERVAL_SECS=5
      - RUST_LOG=info
    depends_on:
      rabbitmq:
        condition: service_healthy

volumes:
  rmq_data:
